sudo: false
language: ruby
cache: bundler
before_install:
   - rvm get head
services:
  - redis-server
script:
  - if [[ "${STYLE}" = "true" ]]; then bundle exec rubocop; fi;
  - bundle exec rspec spec
rvm:
  - jruby-19mode
  - jruby-9.0.4.0
  - rbx-2
  - 2.1.8
  - 2.2.4
  - 2.3.0
env: STYLE=false
gemfile:
  - gemfiles/sidekiq_develop.gemfile
  - gemfiles/sidekiq_2.17.gemfile
  - gemfiles/sidekiq_3.0.gemfile
  - gemfiles/sidekiq_3.1.gemfile
  - gemfiles/sidekiq_3.2.gemfile
  - gemfiles/sidekiq_3.3.gemfile
  - gemfiles/sidekiq_4.0.gemfile
  - gemfiles/sidekiq_4.1.gemfile

notifications:
  email:
    recipients:
      - mikael@zoolutions.se
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.0
      gemfile: gemfiles/sidekiq_develop.gemfile
      env: STYLE=true
addons:
  code_climate:
    repo_token: 88e524e8f638efe690def7a6e2c72b1a9db5cdfa74548921b734d609a5858ee5
