env:
  matrix:
    - COV=false
  global:
    - CC_TEST_REPORTER_ID=88e524e8f638efe690def7a6e2c72b1a9db5cdfa74548921b734d609a5858ee5
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
dist: trusty
sudo: required
language: ruby
cache: bundler
services:
  - redis-server

before_install:
  - gem install bundler -v 2.0.2
  - if [[ "${COV}" = "true" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi;
  - if [[ "${COV}" = "true" ]]; then chmod +x ./cc-test-reporter; fi;

before_script:
  - if [[ "${COV}" = "true" ]]; then ./cc-test-reporter before-build; fi;

script:
  - if [[ "${COV}" = "true" ]]; then bundle exec rubocop -P; fi;
  - if [[ "${COV}" = "true" ]]; then bundle exec reek .; fi;
  - bundle exec rspec --require spec_helper --tag ~perf

after_script:
  - if [[ "${COV}" = "true" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;
rvm:
  - 2.6.2
  - 2.4.6
  - jruby-9.2.7.0

matrix:
  fast_finish: true
  include:
    - rvm: 2.5.5
      gemfile: gemfiles/sidekiq_6.0.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/sidekiq_6.0.gemfile
    - rvm: rbx-4.5
      gemfile: gemfiles/sidekiq_5.2.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/sidekiq_develop.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/sidekiq_6.0.gemfile
      env: COV=true

gemfile:
  - gemfiles/sidekiq_4.0.gemfile
  - gemfiles/sidekiq_4.1.gemfile
  - gemfiles/sidekiq_4.2.gemfile
  - gemfiles/sidekiq_5.0.gemfile
  - gemfiles/sidekiq_5.1.gemfile
  - gemfiles/sidekiq_5.2.gemfile

notifications:
  email:
    recipients:
      - mikael@zoolutions.se
